[MapCalibration]
bPoint1Valid = true
fPoint1WorldX = 19475.414062
fPoint1WorldY = -7408.516602
fPoint1MapU = 0.473988
fPoint1MapV = 0.557441
bPoint2Valid = true
fPoint2WorldX = 174291.890625
fPoint2WorldY = -92643.929688
fPoint2MapU = 0.832586
fPoint2MapV = 0.797381
bPoint3Valid = true
fPoint3WorldX = -64942.992188
fPoint3WorldY = 104648.000000
fPoint3MapU = 0.277120
fPoint3MapV = 0.226989
bPoint4Valid = true
fPoint4WorldX = -33978.324219
fPoint4WorldY = -89423.789062
fPoint4MapU = 0.348518
fPoint4MapV = 0.798418
bPoint5Valid = true
fPoint5WorldX = 135010.281250
fPoint5WorldY = 35013.164062
fPoint5MapU = 0.738511
fPoint5MapV = 0.422961


[Tutorials]

; Internal state used to detect when tutorials are re-enabled
bPreviouslyEnabled = true

; Legacy Welcome tutorial completion state
bWelcomeComplete = true

; Completion bits shared by all RmlUi tutorials
uCompletedMask = 65
