[General]
bVerboseLogging = false
bEditModeEnabled = true
bLockPins = false
bShowTutorials = true


[Interface]
sLanguage = en


[MapMarker]
bEnableMapMarker = true
bDynamicRotation = true
sMarkerNifPath = DragonBoardVR/Player.nif


[QuestMarker]
bEnableQuestMarker = true
fMarkerScale = 0.250000
fRotX = 90.000000
fRotY = 0.000000
fRotZ = 180.000000
iLastFormID = 0
iLastFormID2 = 0
iLastFormID3 = 0
iLastObjectiveID = 0
iLastObjectiveID2 = 0
iLastObjectiveID3 = 0
iLastObjectiveInstanceID = 0
iLastObjectiveInstanceID2 = 0
iLastObjectiveInstanceID3 = 0
iLastQuestInstanceID = 0
iLastQuestInstanceID2 = 0
iLastQuestInstanceID3 = 0
sMarkerNifPath = meshes\DragonBoardVR\QuestMarker.nif


[Activation]
iActivationMode = 6
fHoldTimeGrip = 0.000000
fHoldTimeTrigger = 0.300000
fHoldTimeThumbstick = 0.150000
fHoldTime = 0.200000
bUseLeftHandAsMenu = true
bLastSavedLeftHand = true


[PhysicalBoard]
bEnabled = true
sPlugin = DragonBoardVR.esp
iLocalFormID = 2048
iVrikProxyLocalFormID = 2049
fScale = 1.050000
fMeshScale = 1.000000
fRmlSurfaceOffsetX = 0.000000
fRmlSurfaceOffsetY = 0.000000
fRmlSurfaceOffsetZ = 0.000000
fRmlSurfaceRotX = 90.000000
fRmlSurfaceRotY = 0.000000
fRmlSurfaceRotZ = 180.000000
fRmlSurfaceScale = 1.000000


[Combat]
bSlowTimeOnOpen = false
fSlowTimeMultiplier = 0.250000


[Interaction]
fRaycastMaxDistance = 100.000000
bEnableFingerTouch = true
fFingerTouchEnterDistance = 5.000000
fFingerTouchExitDistance = 6.000000
fHapticIntensity = 0.100000
fHapticDuration = 0.040000


[Debug]
bDebugMode = false
bFingerTrackingProbe = false
bFingerTrackingProbeMarkers = true
fFingerTrackingMarkerScale = 5.000000
fFingerTrackingProbeInterval = 0.250000
fFingerTrackingTipExtension = 2.500000


[FixedWidgets]
iCount = 0


[Wiggle]
bEnableWorldPinWiggle = true
fWigglePosAmplitude = 0.100000
fWiggleRotAmplitude = 3.000000
fWiggleSideAmplitude = 0.040000
fWiggleSpeed = 1.000000


[RmlUi]

; animation preset: radial, reverse radial, Fade, leftToRight, rightToLeft
animationstyle = Fade
bEntranceAnimation = true
bRenderOnDirty = true
fEntranceDuration = 0.250000
fEntranceFeather = 0.100000
iMaxActiveFPS = 60
iRenderHeight = 720
iRenderWidth = 1280


[CategoryOverrides]


[ItemOverrides]
