[MapCalibration]
; Runtime-generated map calibration. This file is managed by DragonBoardVR.
bPoint1Valid = false
fPoint1WorldX = 0.000000
fPoint1WorldY = 0.000000
fPoint1MapU = 0.473988
fPoint1MapV = 0.557441
bPoint2Valid = false
fPoint2WorldX = 0.000000
fPoint2WorldY = 0.000000
fPoint2MapU = 0.832586
fPoint2MapV = 0.797381
bPoint3Valid = false
fPoint3WorldX = 0.000000
fPoint3WorldY = 0.000000
fPoint3MapU = 0.277120
fPoint3MapV = 0.226989
bPoint4Valid = false
fPoint4WorldX = 0.000000
fPoint4WorldY = 0.000000
fPoint4MapU = 0.348518
fPoint4MapV = 0.798418
bPoint5Valid = false
fPoint5WorldX = 0.000000
fPoint5WorldY = 0.000000
fPoint5MapU = 0.738511
fPoint5MapV = 0.422961
